within HeatExchangerExamples;
model TwoPhaseLiquidPlainCounterEvaporator
    extends .HeatExchanger.HeatExchangers.Plate.Experiments.TwoPhaseLiquidPlainCounterEvaporator;
end TwoPhaseLiquidPlainCounterEvaporator;
